### PR TITLE
Enhancements and Bug Fixes for Cross-Platform Consistency #32

### LINKED ISSUE #32: Enhancements and Bug Fixes for Cross-Platform Consistency
Mobile

- [ ] fix tab alignment - Filters(both analytics and datasets)
- [ ] add functionality and fix css for search bar in region selection 
- [x] make whole dataset card tappable
- [x] left align all the 'Show more' buttons (cards, inside dataset page & next to file description)
- [ ] rename title to 'Filters' in Filters bottom sheet
- [x] add homepage mobile designs
- [ ] make header sticky

Desktop

- [x] fix search field issue on Datasets page 
- [x] fix sort by dropdown functionality on Datasets page 
- [x] fix prompt issue when clicking on share dataset(on dataset landing page) for the new tab redirection

----

2026 update: Now invalid (use branding repo):

- fix ASDM logo in footer
- change texts on about us page
- add about us mobile designs

### PR DESCRIPTION
**Pull request by sswadi**
Mobile

- fix tab alignment - Filters(both analytics and datasets)
- add functionality and fix css for search bar in region selection
- make whole dataset card tappable
- left align all the 'Show more' buttons (cards, inside dataset page & next to file description)
- rename title to 'Filters' in Filters bottom sheet
- add about us and homepage mobile designs
- make header sticky

Desktop

- fix search field issue on Datasets page
- fix sort by dropdown functionality on Datasets page
- fix prompt issue when clicking on share dataset(on dataset landing page) for the new tab redirection
- fix ASDM logo in footer
- change texts on about us page

### CODE REVIEW

File: app/[locale]/datasets/components/dataset-layout.tsx [hunk 1]
```diff
@@ -53,20 +89,29 @@ export function Content({
...
-                    <SearchInput
+                    {/* <SearchInput
                       name="search"
                       placeholder="Search by title, description..."
                       onSubmit={() => setQueryString('', { shallow: false })}
                       label="Search"
                       onChange={(value) => setSearchValue(value)}
                       defaultValue={queryString || ''}
                       onClear={() => setQueryString('', { shallow: false })}
+                    /> */}
```
Comment (ruthvik129) [inline app/[locale]/datasets/components/dataset-layout.tsx]: Why are we using textfield instead of search input @sswadi

**Review by ruthvik129 — APPROVED** [review]
